GET http://localhost:8080/doctors?page=0&size=20
Accept: application/json

###
POST http://localhost:8080/doctors
Content-Type: application/json

{
"name": {
  "firstname": "Tytus",
  "surname": "Bomba"
},
"specialization": "DENTIST"
}

###


