GET http://localhost:8080/patients?page=0&size=20
Accept: application/json

###
POST http://localhost:8080/patients
Content-Type: application/json

{
"name": {
  "firstname": "Chorąży",
  "surname": "Głuś"
},
"address": "Kosmos"
}

###


